### ISSUE TITLE
PHP 7.4 deprecates parent for classes without parent

### ISSUE THREAD

**Issue by aanderson-msi** [avadev/AvaTax-Calc-SOAP-PHP#20]
Line 32 of ATConfig.php:
`        if($n == '_ivars') { return parent::__get($n); }`

However, the class is declared without a parent:
```
/**
 * Contains various service configuration parameters as class static variables.
 *
 * {@link AddressServiceSoap} and {@link TaxServiceSoap} read this file during initialization.
 *
 * @author    Avalara
 * @copyright © 2004 - 2011 Avalara, Inc.  All rights reserved.
 * @package   Base
 */
namespace AvaTax;
class ATConfig
{

```
When using this class with PHP 7.4, it results in an error.  
```
Deprecated Functionality: Cannot use "parent" when current class scope has no parent in <project>/vendor/avalara/avatax/AvaTax/ATConfig.php on line 32
``` 
Recommend returning "null" instead of the call to the parent's __get() function.

**Comment by vipinroy** [comment]
Any update on this issue?

**Comment by jonathanribas** [comment]
We can't move forward on PHP upgrades because of this issue.

PHP 7.3 will be deprecated at the of this year, can you please update your code?

**Comment by gusdemayo** [comment]
I opened a pull request that should fix this issue

By removing the line

```
if($n == '_ivars') { return parent::__get($n); }
```

the case of `$n === 'ivars'` should be caught by the else statement

**Comment by jonathanribas** [comment]
Thank you @gusdemayo! I was creating a PR with the exact same change!

**Comment by gusdemayo** [comment]
Is this project still being maintained?

**Comment by asentner** [comment]
This is still an issue. I take it this is no longer maintained?
